### ISSUE TITLE
Support NestJS 12, which is published as pure ESM

### ISSUE THREAD

**Issue by Martin-Bruel** [Martin-Bruel/nestjs-langchain#76]
## Context

`peerDependencies` declares `@nestjs/common` and `@nestjs/core` at `^11.1.18` (#39). NestJS
**12.0.2** is now the current release, so `nest new` produces an application this library
refuses to install into: `npm install nestjs-langchain` ends in `ERESOLVE`, and the way out
is `--legacy-peer-deps`.

Every NestJS application created from today onward is in that situation.

## What was measured

Probed against `@nestjs/common`, `@nestjs/core` and `@nestjs/testing` at 12.0.2, on Node
v22.22.2, using the library built by `tsconfig.build.json`.

**The library itself already works on NestJS 12.** Nothing in `lib/` needs changing:

```
tsc -p tsconfig.build.json          -> exit 0
module registration + run()         -> "42"
tool discovery + zod schema + call  -> 1 tool: add | schema: [a, b] | invoke -> 42
```

That last line matters most. `DiscoveryService`, `MetadataScanner` and the
`host.metatype` identity check in `ToolDiscoveryService` are the internals most likely to
move between majors, and they behave identically.

**One thing breaks, and it is the test runner.** All 4 suites fail to load:

```
Must use import to load ES Module: node_modules/@nestjs/common/index.js
  - Use Node v24.9+ where Jest supports require(esm) natively
```

## The actual change: NestJS 12 is pure ESM

```json
// @nestjs/common@12.0.2, @nestjs/core@12.0.2, @nestjs/testing@12.0.2
{ "type": "module", "exports": { ".": "./index.js" }, "engines": { "node": ">= 20" } }
```

There is no CommonJS entry point any more. A CJS consumer reaches NestJS 12 only through
Node's `require(esm)`, which is unflagged from Node 22.12. Confirmed working on 22.22.2:

```
require('@nestjs/common')  -> OK, 115 exports
```

So the runtime is fine and `jest-runtime` is the gap: it does not implement `require(esm)`
before Node 24.9.

## The decision this issue has to make

Supporting `^11.1.18 || ^12.0.0` means the published CJS build has to load both a CJS
NestJS 11 and an ESM NestJS 12. That works, but only above Node 22.12, while NestJS 12 itself
declares `>= 20`. `engines` cannot express "20 for Nest 11, 22.12 for Nest 12", so one of
these has to be chosen:

1. Keep the CJS build, declare `engines: >= 22.12`, and document why it is stricter than
   NestJS's own floor
2. Ship a dual CJS/ESM build so Node 20 consumers on NestJS 12 are served natively

Option 2 is more work and interacts with #52: this package already gets bitten when the same
dependency is visible through both a `.d.ts` and a `.d.cts`, and dual-publishing turns that
from a hazard we avoid into one we author.

## Acceptance criteria

- [ ] Peer range widened to accept NestJS 12, with the supported range written down
- [ ] A decision recorded between the two options above, with the `engines` floor that follows
- [ ] The test suite runs green against NestJS 12, by raising the CI Node version, moving Jest to ESM mode, or another route
- [ ] CI exercises both majors rather than only the one that happens to resolve
- [ ] README states the supported NestJS and Node ranges
- [ ] Release notes covering the widened peer range and any `engines` change

## Notes

Found while closing #39, whose own note said to keep the range at `^11` and treat `^12` as a
separate decision. This is that decision, and it became urgent when 12.0.2 shipped.

Dependabot PR #71 was trying to pull `@nestjs/platform-express` to 12.0.1 on its own. It
would have taken CI down for exactly the reason above, and it is moot now that
`@nestjs/platform-express` is no longer a declared devDependency.

Reproduction of everything above lives in the probe described in this issue: copy `lib/`,
`tests/` and the configs, `npm i -D @nestjs/common@^12 @nestjs/core@^12 @nestjs/testing@^12`,
then build and run.

**Comment by Martin-Bruel** [comment]
CI now exercises both majors, and the packed artifact with them.

## The suite was already green on NestJS 12

Measured before writing any CI, since it decided whether this was a matrix job or a migration: lint, format, build, all three tsconfigs and the 14 tests pass unchanged against `@nestjs/common`, `@nestjs/core` and `@nestjs/testing` at 12.0.2. No source change was needed, because #77 had already removed the deep imports into `@nestjs/*` internals that would have broken under NestJS 12's `exports` map.

## The matrix

`node: [22, 24]` crossed with `nest: [11, 12]`, four jobs.

The pinning step runs for **both** values rather than only for 12:

```yaml
- name: Pin NestJS ${{ matrix.nest }}
  run: npm i --no-save @nestjs/common@^${{ matrix.nest }} @nestjs/core@^${{ matrix.nest }} @nestjs/testing@^${{ matrix.nest }}
```

Skipping it for 11 would have made the job depend on whichever version the lockfile happens to carry, which is the implicit coupling this issue was about. No `--force`, no `--legacy-peer-deps`: an ERESOLVE there means the declared peer range does not really accept that major.

## What the matrix alone would still have missed

Every step above runs against the sources. None of them touches the `exports` map, the declaration files, or the peer range as npm resolves them, and those only break at install time. That gap is exactly what shipped an ESM package on a manual check that lived in a scratch directory and no longer exists.

`scripts/verify-package.mjs` builds, packs, and installs the tarball into two throwaway consumers, one CommonJS and one ESM. Each is type-checked and booted through `run()`. The CommonJS one uses a real `require`, so Node's `require(esm)` path is covered rather than assumed.

```
CJS consumer          ESM consumer
  installs, peer range accepted
  types resolve
  boots and answers
```

Green on both majors. It runs in the matrix, so it is checked four times per pipeline, and locally through `npm run verify:package -- 12`.

**The check was verified to fail.** Narrowing the peer range back to `^11.1.18` and running against 12 makes both consumers fail on `ERESOLVE`. A gate that cannot fail is not a gate.

## One thing this turned up about #74

`scripts/verify-package.mjs` initially escaped both lint and format, since their scope was `lib/`, `tests/` and `vitest.config.ts`. The same class of gap #74 closed, reopened by the file added to close this one. Scope is now `{lib,tests,scripts}` for oxlint, Prettier and `lint-staged` alike.

## Remaining

Only the release notes, which belong to the release itself. The peer range, the ESM decision and the README ranges were all done in #77.
